### ISSUE TITLE
Crashes upon startup

### ISSUE THREAD

**Issue by vojta-horanek** [out386/AndroidFileHost_Browser#2]
Last versions on XDA Labs crashes upon startup

**Comment by msfjarvis** [comment]
Can you attach a logcat please? Thanks.

**Comment by vojta-horanek** [comment]
This is really weird log, i have never seen someting like this.
[log.txt](https://github.com/out386/AndroidFileHost_Browser/files/737123/log.txt)

(Used android studio to get this)

**Comment by msfjarvis** [comment]
I haven't seen so much JIT spam ever myself. Log's making no sense at all. OS/Device/Android Version ?

**Comment by vojta-horanek** [comment]
5.0.2/VF895N

**Comment by msfjarvis** [comment]
Don't think any of us has tested it on 5.0.1 . Can you try logging the crash using `adb logcat -v tag` after clearing the log buffer using `adb logcat -c` ? Basically : clear buffer, start logging, reproduce crash.

**Comment by vojta-horanek** [comment]
I think its the same, anyway here it is:
[log-adb.txt](https://github.com/out386/AndroidFileHost_Browser/files/737127/log-adb.txt)

**Comment by out386** [comment]
Yeah, this makes no sense. We should have received a Fabric stacktrace, too. Please confirm whether you're using version 1.0.0 of the app. Also, please tell me your phone model.

**Comment by vojta-horanek** [comment]
Iam using the version 1.0.0. My phone model is Vodafone Smart Prime 6 (VF895N)

**Comment by out386** [comment]
OK, checking the cause of the crash.

**Comment by out386** [comment]
One thing, install this, and give another log, if it still crashes.

https://play.google.com/store/apps/details?id=com.google.android.webview

**Comment by vojta-horanek** [comment]
Already installed. I'm on beta channel, gonna try the stable version

**Comment by vojta-horanek** [comment]
It crashes even on stable (closing the issue was a mistake)[log-2.txt](https://github.com/out386/AndroidFileHost_Browser/files/737413/log-2.txt)

**Comment by msfjarvis** [comment]
https://transfer.sh/MuJYV/afh-browser-beta-6.apk

Try this one

**Comment by vojta-horanek** [comment]
It doesnt work :(

**Comment by MaazMuzammil** [comment]
stuck in loading 
ver-1.2.1
tested in all rom

**Comment by out386** [comment]
It'll always be stuck, now, because there's a weird capcha + auth on the API now, and we didn't look at ways to pass it yet.

**Comment by MaazMuzammil** [comment]
Wating for reborn

**Comment by jimbomodder** [comment]
Same as rest, no version loads anymore

**Comment by msfjarvis** [comment]
AndroidFileHost has enforced a captcha on the API which breaks any kind of programmatic access.

**Comment by out386** [comment]
Closing issue as we won't be violating rules by bypassing Cloudflare protection. Sorry for sending you people an email about a year old issue.
