### ISSUE TITLE
Runs in offline constantly

### ISSUE THREAD

**Issue by jimbomodder** [out386/AndroidFileHost_Browser#3]
Updated to 1.1.2 and since I have I'm unable to use it, brings up old cached data only and wiping apks data makes it run in offline mode only

**Comment by out386** [comment]
Please mention the following:
Can you open androidfilehost.com from your phone's browser? 
Which device/s did you try to load files for? Give at least one name.
Pulling down on the list of cached files reloads files from the cache?

**Comment by jimbomodder** [comment]
Yes androidfilehost runs fine from chrome, I've tried on both LG G6 and Nexus 6 and both fail. Sometimes it fails to load device list and says it needs to be connected to internet to work yet it's connected to WiFi.
 Pulling down to refresh gives me the "must be connected to internet to work"  error.

**Comment by jimbomodder** [comment]
Rolling back to V1.1.1 solves the issues

**Comment by out386** [comment]
Try this build, please. Uninstall the existing one first. 
https://drive.google.com/file/d/0By_BpKUWHuI4cU5xYkR4YnhlcVU/view?usp=drivesdk

**Comment by jimbomodder** [comment]
Seems it doesn't work when connected to WiFi but does work on mobile data. I will try a clean install of a fresh os and try again.

**Comment by out386** [comment]
Okay. Do let me know.

**Comment by jimbomodder** [comment]
Sorry for delay, it runs fine now on orignal 1.1.2 once i flashed orea six-rom

**Comment by out386** [comment]
Ok. That's nice.

**Comment by jimbomodder** [comment]
Bugs back, says connect to network regardless if I'm on 4g/3g/wifi
