### ISSUE TITLE
Fails to connect to network

### ISSUE THREAD

**Issue by jimbomodder** [out386/AndroidFileHost_Browser#4]
Used both your beta and original 1.1.2 and sys connect to network. I tried on 4g/3g/WiFi and all says same.

**Comment by out386** [comment]
Try this one, let me know if it works.
https://github.com/out386/AndroidFileHost_Browser/releases/download/v1.2.0/AFH_Browser_v1.2.0.apk

**Comment by jimbomodder** [comment]
Testing now, crashed once with it going into offline mode but only once so far.

**Comment by out386** [comment]
If you get another crash, logs will help.

**Comment by jimbomodder** [comment]
Will do

**Comment by out386** [comment]
Fixed in 1e287c9ebfe5d1f7046d90ae4914deddc66c4550
