### ISSUE TITLE
AFH Not Loading... 

### ISSUE THREAD

**Issue by Ibuprophen** [out386/AndroidFileHost_Browser#5]
After opening the app, it is in a consistent loading as indicated by the animated circle (reflected in the attached screenshot).

[screenshot_20171103-153143](https://user-images.githubusercontent.com/18060271/32392861-b39ceaa4-c0ad-11e7-8e80-f8f7392b61e6.jpg)

**Comment by msfjarvis** [comment]
the API has been blocked by AFH. The app is dead.

**Comment by Ibuprophen** [comment]
That's more than likely because of the recently launched new website interface. 

The new beta api version is, i believe, on the following URL. 

https://androidfilehost.com/api/docs/

I hope it helps you out.

**Comment by out386** [comment]
That's the same API we've been using. The API is no longer supported now.
